platform:
  workload:
    deployment:
      enabled: true
      name: banana-app
      replicaCount: 2
      containers:
        - name: nginx
          enabled: true
          image:
            repository: nginx
            tag: stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: index-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
    service:
      enabled: true
      port: 80

    ingress:
      enabled: true
      host: banana.local

    configmap:
      enabled: true
      items:
        - name: banana-index
          data:
            index.html: "Hello, Banana!"

    volumes:
      - name: index-volume
        configMap:
          name: banana-index
