workload:
  deployment:
    enabled: false
    name: ""
    replicaCount: 1

    containers:
      - name: ""
        enabled: true
        image:
          repository: ""
          tag: ""
        command: []
        args: []
        ports: []
        env: []
        envFrom: []
        resources: {}
        volumeMounts: []
        livenessProbe: {}
        readinessProbe: {}

    initContainers:
      - name: ""
        enabled: false
        image:
          repository: ""
          tag: ""
        command: []
        args: []
        env: []
        envFrom: []
        resources: {}
        volumeMounts: []

    volumes: []

    nodeSelector: {}
    affinity: {}
    tolerations: []

  cronjob:
    enabled: false
    name: ""
    schedule: "*/5 * * * *"
    image:
      repository: ""
      tag: ""
    command: []
    args: []
    env: []
    resources: {}
    volumeMounts: []
    volumes: []

  service:
    enabled: false
    port: 80

  ingress:
    enabled: false
    host: ""

  configmap:
    enabled: false
    items: []

  secret:
    enabled: false
    items: []

  persistentVolumeClaim:
    enabled: false
    items: []
