{{- if .Values.workload.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "base-app.fullname" . }}
  labels:
    app: {{ include "base-app.name" . }}
spec:
  schedule: "{{ .Values.workload.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: job
              image: "{{ .Values.workload.cronjob.image.repository }}:{{ .Values.workload.cronjob.image.tag }}"
              imagePullPolicy: {{ .Values.workload.cronjob.image.pullPolicy | default "IfNotPresent" }}
              {{- if .Values.workload.cronjob.command }}
              command: {{ toJson .Values.workload.cronjob.command }}
              {{- end }}
              {{- if .Values.workload.cronjob.env }}
              env:
                {{- range .Values.workload.cronjob.env }}
                - name: {{ .name }}
                  value: {{ .value | quote }}
                {{- end }}
              {{- end }}
          restartPolicy: OnFailure
{{- end }}
