{{- if .Values.workload.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullname" . }}
  labels:
    app: {{ include "platform.fullname" . }}
spec:
  replicas: {{ .Values.workload.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "platform.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "platform.fullname" . }}
      annotations:
        {{- /* Checksum para reiniciar o pod se ConfigMap/Secret mudar */}}
        {{- if .Values.workload.configmap.enabled }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.workload.secret.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}

    spec:
      {{- if .Values.workload.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.workload.deployment.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.workload.deployment.affinity }}
      affinity:
        {{- toYaml .Values.workload.deployment.affinity | nindent 8 }}
      {{- end }}

      {{- if .Values.workload.deployment.tolerations }}
      tolerations:
        {{- toYaml .Values.workload.deployment.tolerations | nindent 8 }}
      {{- end }}

      {{- if .Values.workload.deployment.initContainers }}
      initContainers:
        {{- range .Values.workload.deployment.initContainers }}
        {{- if .enabled }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- if .command }}
          command: {{ toJson .command }}
          {{- end }}
          {{- if .args }}
          args: {{ toJson .args }}
          {{- end }}
          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}

      containers:
        {{- range .Values.workload.deployment.containers }}
        {{- if .enabled }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"

          {{- if .command }}
          command: {{ toJson .command }}
          {{- end }}

          {{- if .args }}
          args: {{ toJson .args }}
          {{- end }}

          {{- if .ports }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          {{- end }}

          {{- if .env }}
          env:
            {{- range .env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}

          {{- if .envFrom }}
          envFrom:
            {{- toYaml .envFrom | nindent 12 }}
          {{- end }}

          {{- if .volumeMounts }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- end }}

          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}

          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}

          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- end }}

      {{- if .Values.workload.deployment.volumes }}
      volumes:
        {{- toYaml .Values.workload.deployment.volumes | nindent 8 }}
      {{- end }}
{{- end }}
