{{- if .Values.workload.secret.enabled }}
{{- range .Values.workload.secret.items }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "platform.named" (dict "name" .name "suffix" "secret") }}
stringData:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
